### ISSUE TITLE
Missing dependency "active.h"

### ISSUE THREAD

**Issue by FirefoxMetzger** [amarburg/lsd_slam#17]
In file included from /home/user/lsd_slam/lib/SlamSystem.cpp:53:0:
    /home/user/lsd_slam/lib/SlamSystem/MappingThread.h:10:34: fatal error: active_object/active.h: No  
    such file or directory
     #include "active_object/active.h"

Which package does this file come from?
I am running Ubuntu 16.04 , 
Pangolin build separately from source, 
g3log build separately from source (maybe lsd_slam doesn't find it?),
g2o build along lsd_slam

Also I'm building using CMake not rake.

**Comment by amarburg** [comment]
It's from:   https://github.com/amarburg/libactive_object

Normally this is pulled in automatically by https://github.com/amarburg/lsd_slam/blob/master/cmake/BuildLibActiveObject.cmake

called from the top-level CMakeLists.txt (line 52)

**Comment by FirefoxMetzger** [comment]
okay now its building successfully =) thanks a lot.
